version: '3'

services:
  db:
    image: bitnami/mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 80:8000
